### ISSUE TITLE
BUG: Tx task enters infinite loop

### ISSUE THREAD

**Issue by glmnet** [sicrisembay/CANopenNode_ESP32#3]
I have created an issue explaining how this happens here: https://github.com/CANopenNode/CANopenNode/issues/543

Leaving an open issue here also for tracking the bug

**Comment by sicrisembay** [comment]
@glmnet Thank you for reporting this bug.
I just got time to look into this and found that this is caused by a race condition due to misplaced mutex lock on CO_CANsend().
I've fixed this in commit fb1e022956c2106122411906cbb43d0a58739cf8.
Please let me know if this does not fix the issue.

-Sicris
